package main

import "sort"

const DEFUALT_TILE = 1329

var TileNames = map[string]int{
	"water":    0,
	"water2":   1,
	"water_tl": 2,
	"water_t":  3,
	"water_tr": 4,
	"water_bl": 114,
	"water_b":  115,
	"water_br": 116,
	"water_cl": 58,
	"water_c":  59,
	"water_cr": 60,

	"green_ground":  5,
	"green_ground2": 61,

	"brown_ground":  6,
	"brown_ground2": 62,

	"gray_ground":  7,
	"gray_ground2": 63,

	"tan_ground":  8,
	"tan_ground2": 64,
	"pebbles":     9,

	"pebbled_grass": 65,

	"water_corner_br": 56,
	"water_corner_bl": 57,
	"water_corner_tr": 112,
	"water_corner_tl": 113,

	"held_water": 227,

	"held_water_bl":        282,
	"held_water_b":         283,
	"held_water_br":        284,
	"held_water_tl":        170,
	"held_water_t":         171,
	"held_water_tr":        172,
	"held_water_cl":        226,
	"held_water_cr":        228,
	"held_water_corner_tr": 224,
	"held_water_corner_tl": 225,
	"held_water_corner_br": 168,
	"held_water_corner_bl": 169,

	"red_flower_tl": 338,
	"red_flower_t":  339,
	"red_flower_tr": 340,
	"red_flower_cl": 394,
	"red_flower":    395,
	"red_flower_cr": 396,

	"red_flower_bl": 450,
	"red_flower_b":  451,
	"red_flower_br": 452,

	"red_flower_corner_tl": 393,
	"red_flower_corner_tr": 392,
	"red_flower_corner_bl": 337,
	"red_flower_corner_br": 336,

	"white_flower_tl": 338 + 56*3,
	"white_flower_t":  339 + 56*3,
	"white_flower_tr": 340 + 56*3,
	"white_flower_cl": 394 + 56*3,
	"white_flower":    395 + 56*3,
	"white_flower_cr": 396 + 56*3,

	"white_flower_bl": 450 + 56*3,
	"white_flower_b":  451 + 56*3,
	"white_flower_br": 452 + 56*3,

	"white_flower_corner_tl": 393 + 56*3,
	"white_flower_corner_tr": 392 + 56*3,
	"white_flower_corner_bl": 337 + 56*3,
	"white_flower_corner_br": 336 + 56*3,

	"dirt_path":         568,
	"dirt_path_cl":      567,
	"dirt_path_cr":      569,
	"dirt_path_t":       512,
	"dirt_path_tl":      511,
	"dirt_path_tr":      513,
	"dirt_path_b":       624,
	"dirt_path_bl":      623,
	"dirt_path_br":      625,
	"dirt_path_b_end":   621,
	"dirt_path_t_end":   622,
	"dirt_path_r_end":   677,
	"dirt_path_l_end":   678,
	"dirt_path_x":       457,
	"dirt_path_y":       401,
	"dirt_path_turn_tr": 455,
	"dirt_path_turn_tl": 456,
	"dirt_path_turn_br": 399,
	"dirt_path_turn_bl": 400,
	"dirt_path_4way":    679,
	"dirt_path_ltr":     454,
	"dirt_path_trb":     453,
	"dirt_path_rbl":     397,
	"dirt_path_blu":     398,

	"gray_path":         568 + 56*6,
	"gray_path_cl":      567 + 56*6,
	"gray_path_cr":      569 + 56*6,
	"gray_path_t":       512 + 56*6,
	"gray_path_tl":      511 + 56*6,
	"gray_path_tr":      513 + 56*6,
	"gray_path_b":       624 + 56*6,
	"gray_path_bl":      623 + 56*6,
	"gray_path_br":      625 + 56*6,
	"gray_path_b_end":   621 + 56*6,
	"gray_path_t_end":   622 + 56*6,
	"gray_path_r_end":   677 + 56*6,
	"gray_path_l_end":   678 + 56*6,
	"gray_path_x":       457 + 56*6,
	"gray_path_y":       401 + 56*6,
	"gray_path_turn_tr": 455 + 56*6,
	"gray_path_turn_tl": 456 + 56*6,
	"gray_path_turn_br": 399 + 56*6,
	"gray_path_turn_bl": 400 + 56*6,
	"gray_path_4way":    679 + 56*6,
	"gray_path_ltr":     454 + 56*6,
	"gray_path_trb":     453 + 56*6,
	"gray_path_rbl":     397 + 56*6,
	"gray_path_blu":     398 + 56*6,

	"white_path":         568 + 56*12,
	"white_path_cl":      567 + 56*12,
	"white_path_cr":      569 + 56*12,
	"white_path_t":       512 + 56*12,
	"white_path_tl":      511 + 56*12,
	"white_path_tr":      513 + 56*12,
	"white_path_b":       624 + 56*12,
	"white_path_bl":      623 + 56*12,
	"white_path_br":      625 + 56*12,
	"white_path_b_end":   621 + 56*12,
	"white_path_t_end":   622 + 56*12,
	"white_path_r_end":   677 + 56*12,
	"white_path_l_end":   678 + 56*12,
	"white_path_x":       457 + 56*12,
	"white_path_y":       401 + 56*12,
	"white_path_turn_tr": 455 + 56*12,
	"white_path_turn_tl": 456 + 56*12,
	"white_path_turn_br": 399 + 56*12,
	"white_path_turn_bl": 400 + 56*12,
	"white_path_4way":    679 + 56*12,
	"white_path_ltr":     454 + 56*12,
	"white_path_trb":     453 + 56*12,
	"white_path_rbl":     397 + 56*12,
	"white_path_blu":     398 + 56*12,
}

//Maps the aesthetic tiles back to their worldly counterparts - border to center
var MapToDefualt = map[string]int{
	"dirt_path":    TileNames["dirt_path"],
	"dirt_path_cl": TileNames["dirt_path"],
	"dirt_path_cr": TileNames["dirt_path"],
	"dirt_path_t":  TileNames["dirt_path"],
	"dirt_path_tl": TileNames["dirt_path"],
	"dirt_path_tr": TileNames["dirt_path"],
	"dirt_path_b":  TileNames["dirt_path"],
	"dirt_path_bl": TileNames["dirt_path"],
	"dirt_path_br": TileNames["dirt_path"],

	"gray_path":    TileNames["gray_path"],
	"gray_path_cl": TileNames["gray_path"],
	"gray_path_cr": TileNames["gray_path"],
	"gray_path_t":  TileNames["gray_path"],
	"gray_path_tl": TileNames["gray_path"],
	"gray_path_tr": TileNames["gray_path"],
	"gray_path_b":  TileNames["gray_path"],
	"gray_path_bl": TileNames["gray_path"],
	"gray_path_br": TileNames["gray_path"],

	"white_path":    TileNames["white_path"],
	"white_path_cl": TileNames["white_path"],
	"white_path_cr": TileNames["white_path"],
	"white_path_t":  TileNames["white_path"],
	"white_path_tl": TileNames["white_path"],
	"white_path_tr": TileNames["white_path"],
	"white_path_b":  TileNames["white_path"],
	"white_path_bl": TileNames["white_path"],
	"white_path_br": TileNames["white_path"],

	"white_flower":           TileNames["white_flower"],
	"white_flower_tl":        TileNames["white_flower"],
	"white_flower_t":         TileNames["white_flower"],
	"white_flower_tr":        TileNames["white_flower"],
	"white_flower_cl":        TileNames["white_flower"],
	"white_flower_cr":        TileNames["white_flower"],
	"white_flower_bl":        TileNames["white_flower"],
	"white_flower_b":         TileNames["white_flower"],
	"white_flower_br":        TileNames["white_flower"],
	"white_flower_corner_tl": TileNames["white_flower"],
	"white_flower_corner_tr": TileNames["white_flower"],
	"white_flower_corner_bl": TileNames["white_flower"],
	"white_flower_corner_br": TileNames["white_flower"],

	"red_flower":           TileNames["red_flower"],
	"red_flower_tl":        TileNames["red_flower"],
	"red_flower_t":         TileNames["red_flower"],
	"red_flower_tr":        TileNames["red_flower"],
	"red_flower_cl":        TileNames["red_flower"],
	"red_flower_cr":        TileNames["red_flower"],
	"red_flower_bl":        TileNames["red_flower"],
	"red_flower_b":         TileNames["red_flower"],
	"red_flower_br":        TileNames["red_flower"],
	"red_flower_corner_tl": TileNames["red_flower"],
	"red_flower_corner_tr": TileNames["red_flower"],
	"red_flower_corner_bl": TileNames["red_flower"],
	"red_flower_corner_br": TileNames["red_flower"],

	"water":    TileNames["water"],
	"water2":   TileNames["water"],
	"water_tl": TileNames["water"],
	"water_t":  TileNames["water"],
	"water_tr": TileNames["water"],
	"water_bl": TileNames["water"],
	"water_b":  TileNames["water"],
	"water_br": TileNames["water"],
	"water_cl": TileNames["water"],
	"water_c":  TileNames["water"],
	"water_cr": TileNames["water"],

	"held_water_bl":        TileNames["held_water"],
	"held_water_b":         TileNames["held_water"],
	"held_water_br":        TileNames["held_water"],
	"held_water_tl":        TileNames["held_water"],
	"held_water_t":         TileNames["held_water"],
	"held_water_tr":        TileNames["held_water"],
	"held_water_cl":        TileNames["held_water"],
	"held_water_cr":        TileNames["held_water"],
	"held_water_corner_tr": TileNames["held_water"],
	"held_water_corner_tl": TileNames["held_water"],
	"held_water_corner_br": TileNames["held_water"],
	"held_water_corner_bl": TileNames["held_water"],
}

var ReverseTileNames = map[int]string{}
var JustNames = []string{}
var WorldlyTiles = []string{
	"water", "held_water", "dirt_path", "gray_path", "white_path", "red_flower", "white_flower",
}

func init() {
	for k, v := range TileNames {
		ReverseTileNames[v] = k
	}
	for k := range TileNames {
		JustNames = append(JustNames, k)
	}
	sort.Strings(JustNames)

}
